### PR TITLE
Updated README.md to reflect added ID functionality

### PR DESCRIPTION
**Pull request by ParticularMiner**
Hi @Bergvca, @justasojourner 

I have updated the documentation [README.md](https://github.com/ParticularMiner/string_grouper/blob/my_update_docs/README.md) to reflect the added ID functionality for functions match_most_similar() and group_similar_strings().  Do let me know if you find any typos or have other suggestions.

### CODE REVIEW

**Review by Bergvca — APPROVED** [review]
Awesome! I will look at adding code-coverage as a badge and number of downloads as well.

**Comment by ParticularMiner** [comment]
Thanks!  Just discovered the world of badges myself and thought they were cool.  Have fun!

**Comment by ParticularMiner** [comment]
I see you've already added the CodeCov badge.  Nice!  
I'm also just now discovering what "code coverage" means.  
Is 98% good enough?  Is it important to get it to 100%?  If so how? (I thought the unit tests covered everything.)

**Comment by ParticularMiner** [comment]
Aha! Clicking on codecov.io badge eventually leads me to the coverage report showing which lines of code were missed.  Nothing too serious, it seems.  Good.

Looks like you've been using coverage.py to generate the reports, then uploading them to codecov.io?  Do you do this manually or automatically through a CI provider?  (I'm only asking for future reference.)

**Comment by Bergvca** [comment]
100% is a nice to have, but in our case it doesn't add to much (just a nice 100% sign on the front page :)). 

I saw you already created a PR so you noticed this but the "high" level functions just call the StringGrouper class (which is tested completely). The exception that is missed should actually be tested, so it's nice to have this codecov overview. Otherwise it would have been missed. I'll have a look at the PR later :) 

Currently I added it manually - maybe at some point I'll add a CI provider, but for now I don't think its really needed.

**Comment by ParticularMiner** [comment]
Agreed.

**Pull request merged**
