### PR TITLE
Update documentation for added ID parameter & tutorial written

### PR DESCRIPTION
**Pull request by justasojourner**
Hi @Bergvca 

Documentation as discussed. I trust OK for you, it is a bit 'chatty' I see the audience though as people who are happy to _benefit_ from String Grouper — without necessarily understanding _the mathematics_ of how it all works.

I changed some text in the README and setup.py files, mainly typos.

I made a tutorials directory to drop the document & supporting file in there to avoid cluttering up the base directory.

I would like to squash/merge the commits so there is only one clean commit to your master branch, but I see that you need to do that when you accept the pull request.

https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-request-merges

I will leave that to you.

If you want the docs less chatty let me know ;)

### CODE REVIEW

**Comment by justasojourner** [comment]
> **Typo**: All functions are **build** [**built**] using a class StringGrouper.

@ParticularMiner - can you batch up any typos, language inconsistencies, you find and send them to me as one file so I can do them all in one go.

**Comment by ParticularMiner** [comment]
Please do diff on attached files to see proposed changes/corrections.

Henry

**Comment by Bergvca** [comment]
Perfect! i saw you were still doing some changes - is this PR now ready? Or do you still want to make some changes?

**Comment by justasojourner** [comment]
> Perfect! i saw you were still doing some changes - is this PR now ready? Or do you still want to make some changes?

Just a one more minor commit from @ParticularMiner to merge into the PR :) then it will be ready. I’ll sent an update message when it’s ready (latest tomorrow) then you can go for it.

**Comment by justasojourner** [comment]
Hi @Bergvca - it's done. I made last changes myself - it was getting down to arcane discussions on English. 

Please do final review. Look forward to seeing it done and promoting the package.

Please don't forget to do a 'Squash and merge' merge, don't want people seeing all the messy 'back and forward' commits :)

github_squash_merge

**Comment by justasojourner** [comment]
@Bergvca - I am finding out with GitHub how to get my email out of the commit message, both I and @ParticularMiner would like it if our emails could be remove. Could you not delete both PRs for the moment. We may have to 'Revert' and re-commit.

We will get back to you as soon as possible. Apologies for any hassle.

**Pull request merged**
