### PR TITLE
Added ignore case functionality

### PR DESCRIPTION
**Pull request by flindeberg**
Needed "ignore case" for my use-case, so creating a PR for it as well.
Setting "ignore case" to on by default, as I found that more useful.

### CODE REVIEW

**Comment by flindeberg** [comment]
Solves #5

**Comment by Bergvca** [comment]
Hi @flindeberg, 
Thanks for this pull request! 

I think it makes sense and agree that this is probably the most used sensible default setting. Could you add a unit test that shows that n_grams indeed changes the string to lowercase based on the settings? Maybe something like test_n_grams_changes_to_lower_case and test_n_grams_remains_uppper_case (when the settings are changed?). Thanks!

**Comment by flindeberg** [comment]
@Bergvca,
Fixed according to your request. 
Holler if there is something more!

**Comment by Bergvca** [comment]
Hi Flindeberg, looks great, thanks!

**Pull request merged**
