### PR TITLE
Add simple test workflow

### PR DESCRIPTION
**Pull request by StevenMaude**
Run tests on pull requests, and on push to main branch.

### CODE REVIEW

**Comment by StevenMaude** [comment]
NB: a couple of tests fail right now for me [running on GitHub](https://github.com/StevenMaude/string_grouper/pull/2/checks?sha=b57559cc8c2bf062095f1d9837d0607f42ef668e).

```
...................................F.F............../home/runner/work/string_grouper/string_grouper/string_grouper_utils/string_grouper_utils.py:152: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  return timestamps.transform(lambda x: np.datetime64(x))
..../home/runner/work/string_grouper/string_grouper/string_grouper_utils/string_grouper_utils.py:146: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  return timestamps.transform(lambda x: np.datetime64(parse(x, parserinfo, **kwargs)))
......
======================================================================
FAIL: test_match_list_diagonal (string_grouper.test.test_string_grouper.StringGrouperTest)
test fails whenever _matches_list's number of self-joins is not equal to the number of strings
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/string_grouper/string_grouper/string_grouper/test/test_string_grouper.py", line 204, in test_match_list_diagonal
    self.assertEqual(num_self_joins, num_strings)
AssertionError: 5 != 6

======================================================================
FAIL: test_match_list_symmetry_without_symmetrize_function (string_grouper.test.test_string_grouper.StringGrouperTest)
mocks StringGrouper._symmetrize_matches_list so that this test fails whenever _matches_list is
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/unittest/mock.py", line 1256, in patched
    return func(*args, **keywargs)
  File "/home/runner/work/string_grouper/string_grouper/string_grouper/test/test_string_grouper.py", line 175, in test_match_list_symmetry_without_symmetrize_function
    self.assertTrue(intersection.empty or len(upper) == len(upper_prime) == len(intersection))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 62 tests in 0.830s

FAILED (failures=2)
```

**Comment by ParticularMiner** [comment]
Hi @StevenMaude ,

These are intentional (that is, those tests are expected to fail).  So nothing to worry about.  ;)



> NB: a couple of tests fail right now for me [running on GitHub](https://github.com/StevenMaude/string_grouper/pull/2/checks?sha=b57559cc8c2bf062095f1d9837d0607f42ef668e).
> 
> ```
> ...................................F.F............../home/runner/work/string_grouper/string_grouper/string_grouper_utils/string_grouper_utils.py:152: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
>   return timestamps.transform(lambda x: np.datetime64(x))
> ..../home/runner/work/string_grouper/string_grouper/string_grouper_utils/string_grouper_utils.py:146: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
>   return timestamps.transform(lambda x: np.datetime64(parse(x, parserinfo, **kwargs)))
> ......
> ======================================================================
> FAIL: test_match_list_diagonal (string_grouper.test.test_string_grouper.StringGrouperTest)
> test fails whenever _matches_list's number of self-joins is not equal to the number of strings
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/runner/work/string_grouper/string_grouper/string_grouper/test/test_string_grouper.py", line 204, in test_match_list_diagonal
>     self.assertEqual(num_self_joins, num_strings)
> AssertionError: 5 != 6
> 
> ======================================================================
> FAIL: test_match_list_symmetry_without_symmetrize_function (string_grouper.test.test_string_grouper.StringGrouperTest)
> mocks StringGrouper._symmetrize_matches_list so that this test fails whenever _matches_list is
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/unittest/mock.py", line 1256, in patched
>     return func(*args, **keywargs)
>   File "/home/runner/work/string_grouper/string_grouper/string_grouper/test/test_string_grouper.py", line 175, in test_match_list_symmetry_without_symmetrize_function
>     self.assertTrue(intersection.empty or len(upper) == len(upper_prime) == len(intersection))
> AssertionError: False is not true
> 
> ----------------------------------------------------------------------
> Ran 62 tests in 0.830s
> 
> FAILED (failures=2)
> ```

**Comment by Bergvca** [comment]
Hi @ParticularMiner  - Sorry i guess I missed this when merging the PR's - we should not have failing tests. That kind of defeats the purpose of unittests as a way to quickly identify new issues. These two are fixed easily by changing assertEqual to assertNotEqual and assertTrue to assertFalse. I can do that now and update the pypi version as well. 

@StevenMaude thanks for this! We are using codecov as well, but it is currently not automated yet. Is that something you can add as well?

**Comment by ParticularMiner** [comment]
Hi @Bergvca, 

I completely agree that all tests should pass.  Actually, it feels better that way to me too.  But I'm still getting used to the philosophy of unit-tests so I wasn't sure, otherwise I would have checked with you again about them myself.

**Comment by ParticularMiner** [comment]
Hi @StevenMaude 

Sorry, I too should have thanked you before for this.  Indeed it would certainly be great if the code coverage report and badge could be automated through a GitHub test workflow..  Very handy and professional!  I'm eager to see how that is done.  

By the way, could you also try automating the test on a Windows 10 operating system, because on my Windows 10 laptop two more test-units (not written by me) fail due to an integer datatype mismatch (a bug which seems to be well-known in the python community).  See the following link for a description: https://stackoverflow.com/questions/57803232/interpreting-numpy-int64-datatype-as-native-int-datatype-in-python-on-windows-x6

**Comment by ParticularMiner** [comment]
Hi @Bergvca @StevenMaude 

I hereby provide the message-logs for the two additional failing tests:

```
============================= ERRORS =============================
Traceback (most recent call last):
  File "C:\Users\username\eclipse-workspace\string_grouper\string_grouper\test\test_string_grouper.py", line 362, in test_case_insensitive_build_matches_list
    pd.testing.assert_frame_equal(expected_df, sg._matches_list)
  File "C:\Users\username\.virtualenvs\string_grouper\lib\site-packages\pandas\_testing.py", line 1704, in assert_frame_equal
    assert_series_equal(
  File "C:\Users\username\.virtualenvs\string_grouper\lib\site-packages\pandas\_testing.py", line 1402, in assert_series_equal
    assert_attr_equal("dtype", left, right, obj=f"Attributes of {obj}")
  File "C:\Users\username\.virtualenvs\string_grouper\lib\site-packages\pandas\_testing.py", line 917, in assert_attr_equal
    raise_assert_detail(obj, msg, left_attr, right_attr)
  File "C:\Users\username\.virtualenvs\string_grouper\lib\site-packages\pandas\_testing.py", line 1073, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: Attributes of DataFrame.iloc[:, 0] (column name="master_side") are different

Attribute "dtype" are different
[left]:  int64
[right]: int32

 
Traceback (most recent call last):
  File "C:\Users\username\eclipse-workspace\string_grouper\string_grouper\test\test_string_grouper.py", line 350, in test_build_matches_list
    pd.testing.assert_frame_equal(expected_df, sg._matches_list)
  File "C:\Users\username\.virtualenvs\string_grouper\lib\site-packages\pandas\_testing.py", line 1704, in assert_frame_equal
    assert_series_equal(
  File "C:\Users\username\.virtualenvs\string_grouper\lib\site-packages\pandas\_testing.py", line 1402, in assert_series_equal
    assert_attr_equal("dtype", left, right, obj=f"Attributes of {obj}")
  File "C:\Users\username\.virtualenvs\string_grouper\lib\site-packages\pandas\_testing.py", line 917, in assert_attr_equal
    raise_assert_detail(obj, msg, left_attr, right_attr)
  File "C:\Users\username\.virtualenvs\string_grouper\lib\site-packages\pandas\_testing.py", line 1073, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: Attributes of DataFrame.iloc[:, 0] (column name="master_side") are different

Attribute "dtype" are different
[left]:  int64
[right]: int32

```

**Comment by StevenMaude** [comment]
@Bergvca @ParticularMiner Thanks for looking at the PR :eyes:

And, of course, for working on the library, which I'd been using and thought it was worth maybe making a small contribution back :+1:

Good questions which are slightly on the edge of my knowledge :slightly_smiling_face:

* Codecov shouldn't be too complicated, from a quick look around. Personally I haven't used codecov before. But there's [an Action](https://github.com/codecov/codecov-action) from Codecov for this purpose. My intuition is that this should be a separate workflow from the test workflow to run only when a commit is pushed to your main branch, e.g. on merging a PR.
* Testing on Windows also should be doable, though I haven't done this before on GitHub either. Hopefully, it doesn't need much more configuration, because the commands run on Linux and Windows should be the same, I think. For example, look at the test workflow for [Black](https://github.com/psf/black/blob/2116eca51f1108ebc924185c87bc363d8e0329b3/.github/workflows/test.yml).

I'll try take a look at these over the next week, though it may be next weekend when I can spend a bit more time checking up on these.

**Comment by ParticularMiner** [comment]
Many thanks @StevenMaude for the very useful links.  I might try them out myself.

**Comment by ParticularMiner** [comment]
I agree with your intuition for separate actions.  It appears Github allows multiple actions, right?  Anyway, a modular design structure for pretty much anything is often a good idea.

**Comment by StevenMaude** [comment]
I rebased this branch on current `master` which fixes the tests on Ubuntu.

The tests [now run on Windows too](https://github.com/StevenMaude/string_grouper/actions/runs/741960285), but they fail as [per the comment above](https://github.com/Bergvca/string_grouper/pull/44#issuecomment-817369576).

**Comment by ParticularMiner** [comment]
Excellent!  Many thanks @StevenMaude !

How do I get your GitHub actions into my own fork of this repository?  Do you need to create a PR for it on my branch too?
I would like to run these tests myself on my fork and see if I can fix the Windows 10 error without breaking the Ubuntu tests.

**Comment by ParticularMiner** [comment]
> How do I get your GitHub actions into my own fork of this repository? Do you need to create a PR for it on my branch too?
> I would like to run these tests myself on my fork and see if I can fix the Windows 10 error without breaking the Ubuntu tests.

I figured it out.  I seem to have fixed the Windows 10 problem too (for now).

**Comment by StevenMaude** [comment]
@ParticularMiner:

> How do I get your GitHub actions into my own fork of this repository? Do you need to create a PR for it on my branch too?

Responding to your question seeing as I was already writing the response. At the command-line, the way I would do this is probably something like:

1. Add the fork as a `git remote` to your local copy of your repository: `git remote add sm git@github.com:StevenMaude/string_grouper.git`
2. Fetch the fork's commits: `git fetch sm`
3. Checkout the fork's branch of interest: `git checkout sm/add-test-workflow`.
4. Checkout a new local branch based on that branch's commit: `git checkout -b add-test-workflow`.
4. Then push the new local branch to your own remote fork on GitHub: `git push origin HEAD`

If you're working in GitHub's web UI, I'm not sure there is an easy way beyond copy-paste. Anyway, you got something working well enough :slightly_smiling_face:

**Comment by StevenMaude** [comment]
While I'm here, I'll also add that a codecov workflow could be a separate PR, as another feature.

**Comment by ParticularMiner** [comment]
Thanks @StevenMaude 

I ended up using the GitHub web GUI but the git method is also useful to know. 

> @ParticularMiner:
> 
> > How do I get your GitHub actions into my own fork of this repository? Do you need to create a PR for it on my branch too?
> 
> Responding to your question seeing as I was already writing the response. At the command-line, the way I would do this is probably something like:
> 
> 1. Add the fork as a `git remote` to your local copy of your repository: `git remote add sm git@github.com:StevenMaude/string_grouper.git`
> 2. Fetch the fork's commits: `git fetch sm`
> 3. Checkout the fork's branch of interest: `git checkout sm/add-test-workflow`.
> 4. Checkout a new local branch based on that branch's commit: `git checkout -b add-test-workflow`.
> 5. Then push the new local branch to your own remote fork on GitHub: `git push origin HEAD`
> 
> If you're working in GitHub's web UI, I'm not sure there is an easy way beyond copy-paste. Anyway, you got something working well enough 🙂

**Comment by ParticularMiner** [comment]
> While I'm here, I'll also add that a codecov workflow could be a separate PR, as another feature.

For your information,  clicking on the codecov badge on README.md will eventually lead you to an old code coverage report at https://codecov.io/gh/Bergvca/string_grouper

**Comment by Bergvca** [comment]
Thanks guys! I will merge this now - agreed that codecov should be a seperate PR

**Pull request merged**
