### PR TITLE
added StringGrouper attribute function _get_true_max_n_matches()

### PR DESCRIPTION
**Pull request by ParticularMiner**
Hi @Bergvca ,

I found a better way (I hope) to deal with the `min_similarity <= 0` issue when `max_n_matches` is too small.

This time StringGrouper is able to determine the correct value for `max_n_matches` automatically by means of a new attribute function `_get_true_max_n_matches()`, but it only does so when `min_similarity <= 0`.

So now when `min_similarity <= 0` and `include_zeroes = True` (the default) and `max_n_matches` is set too small, then an error is raised.  The error message suggests the correct value of `max_n_matches` to use.  It also suggests that the user not set `max_n_matches` at all (to allow StringGrouper to automatically use the correct value).

What are your thoughts on this?

### CODE REVIEW

**Comment by ParticularMiner** [comment]
@Bergvca 

Optimally, the true value for max_n_matches should be returned by `awesome_cossim_topn` from the package [`sparse_dot_topn`](https://github.com/ing-bank/sparse_dot_topn) (by [ing-bank](https://github.com/ing-bank/sparse_dot_topn)).  It is a simple addition (I think) to make to their routine.  I'll see if I can convince them to add it to their package.

**Comment by ParticularMiner** [comment]
Hi @Bergvca ,

It turns out that `._symmetrice_matches_list()` (which used the `pandas` function `combine_first()`) was not optimal at all. Especially for large datasets, it was the bottle-neck during runtime.  

I found a much easier and faster way using scipy's `lil` sparse matrix module and achieved a performance boost both memory-wise and speed-wise (boost x5).

**Comment by ParticularMiner** [comment]
@Bergvca ,

The _get_matches_list function was also reimplemented and given speed-boost of x33  !

**Comment by Bergvca** [comment]
Hi @ParticularMiner 

Just to summarize if I understand this correctly - 

* You've added a method that calculates the maximum possible number of matches. 
* This works by checking, for each row in matrix A, if there are values in the corresponding column in matrix B, is that correct?
* You've found that doing this directly in the sparse_dot_topn function is much faster, and added it in that repo
    * As a sidenote - it's not doing the "topn" part anymore then right? :P 
* The idea is that they will merge it in their branch, and we will use it after that, correct?
* You also updated _symmetrize_matrix function to improve the speed. 

Are those points correct?

Some questions:
- Could you add the _symmetrize_matrix in a separate pull request? Because this one won't be necessary anymore right?
- If your PR is merged in the sparse_dot_topn repo, will we use it by default? How much extra time does this calculation take approximately (as a percentage of the total time)? 

Overall I think its very cool!

**Comment by ParticularMiner** [comment]
Hi @Bergvca ,

You are right on all points.  There's just one thing that I changed only yesterday for `sparse_dot_topn`:

The 'topn' part is still there but no longer necessary for `string_grouper`.  The main advantage now is that specifying `ntop` does not result in a greater-than-necessary memory allocation., enabling `sparse_dot_topn` and consequently `string_grouper` to handle much larger datasets (sometimes a 100 times larger than the current limit) without running into an out-of-memory exception.  

This also means `string_grouper` can now simply choose as the default `max_n_matches = len(duplicates)` (to get all matches above the threshold similarity).  Only if the user really wants less than that can he/she set it as desired.

> * Could you add the _symmetrize_matrix in a separate pull request? Because this one won't be necessary anymore right?
> * If your PR is merged in the sparse_dot_topn repo, will we use it by default? How much extra time does this calculation take approximately (as a percentage of the total time)?
> 
> Overall I think its very cool!

Thanks!  Sure, I can do a separate PR for `_symmetrize_matrix`.   Regarding the timings, I have not measured exactly what you are asking for.  But roughly, I have compared the previous `sparse_dot_topn` timings to the new version's timings which include the extra calculations (note that the extra calculations occur at the same time the matrix product is being computed \[that is, they are not a separate function\]), and surprisingly I found that more often than not the new version was faster than the old despite the extra computations.  I'm not sure why.  But perhaps this may be due to the much much lower memory overhead the new version has while the computations are going on.

One question: do you prefer to have the ing-bank group update their package first so that we continue to use it as an external package that `string_grouper` depends on?  Or should we have our own dedicated `sparse_dot_topn` specially tailored for `string_grouper`?  FYI, I already have a branch (called 'free') with a dedicated `sparse_dot_topn` that I can readily create a PR out of, if you prefer that.

**Comment by ParticularMiner** [comment]
Hi @Bergvca ,

Another thing with the new `sparse_dot_topn`: when the user sets `max_n_matches`, `string_grouper` can now tell whether `max_n_matches` was high enough to capture all matches above the similarity-threshold (since the true `max_n_matches` was computed alongside the matrix-product).  Because of this

1. `string_grouper` may inform the user of this;

2. `string_grouper` can decide whether symmetrizing the matches-matrix is necessary or not; and

3. when `min_similarity` &leq; 0 and `include_zeroes=True`, `string_grouper` can safely pad the matches-list with the zero-similarity pairs of strings if the given value of `max_n_matches` &geq; the true `max_n_matches` returned by `sparse_dot_topn`, or raise an exception if not.

**Comment by ParticularMiner** [comment]
Notify @Bergvca :

# Table of average time-durations of `awesome_cossim_dotn` 

### (for the old and new versions) over 64 random samples of matrix-pairs _A_ and _B_.

The column-names show which one of the two programming languages, python or C/C++, allocated the memory for the result.

Time is measured in seconds (on my 16GB RAM, Intel Core i7 CPU @2.20 GHz laptop).  

ntop = 1000
threshold = 0.01
density = 1e-06
nr_vocab = 33554432 (the number of columns of _A_ ***and*** the number of rows of _B_)
len(master) = 1000000 (the number of rows of _A_)
len(duplicates) = 1000 (the number of columns of _B_)
nnz_A = 33554432
nnz_B = 33554

Note that the new version computes the matrix-product _A_*_B_ while also computing extra information (namely, the true maximum number of matches above the threshold similarity per row of the matrix-product _A_\*_B_); the old version does not compute any extra information.

|#threads| **python (old)**|**python (new)**|**C/C++ (new)**|
|---:|---:|---:|---:|
|0|         1.834083|         1.868284  |1.869601|
|1|         1.927926|        1.906658  |1.924269|
|2|         1.169194|        1.117472  |1.115825|
|3|         0.990708|        0.926965  |0.943591|
|4|         0.905201|        0.859040  |0.871680|
|5|         0.799211|        0.749995  |0.764587|
|6|         0.724956|        0.673326  |0.681706|
|7|         0.661175|        0.609775  |0.614331|

**Comment by ParticularMiner** [comment]
Hi @Bergvca ,

Sorry, I just realized that the previous test samples were somewhat unrealistic: for instance, n_vocab was untypically large for such a small density.  Thus the product-matrix ***A***\****B*** had far too few nonzero elements.  Actually, I had blindly re-used the values I saw in some python scripts in the `sparse_dot_topn` package. 

A more typical sample would have n_vocab ~ 26<sup>3</sup> (for 3-grams of the Latin alphabet); with density ~ 30/n_vocab (for 30-character-length  strings).    So I re-run the tests with these values instead and it became clear that the C/C++ memory allocations do in fact slow the program down considerably (almost 4 times!).  So I apologize again for the previous misleading claims.

In the end, I find it is better to have a separate fast "*scouting*" function that, before the actual computation, goes ahead and determines the amount of space needed for the memory allocation.  Python then makes the allocation using the information gathered by the "*scout*", and performs the matrix-product computation.  Here are the results from the improved tests:

---

### Table comparing average time-durations of `awesome_cossim_dotn` (for the old and new versions) over 16 random samples of typical language-processing matrix-pairs _A_ and _B_.


The column-names show how the memory was allocated for the matrix-product result &mdash; either the size was 
1. overestimated as `ntop*A.shape[0]`, or
2. determined exactly by the '*scout*' function before the actual computation.

Remember that the old version had no *scouting* function.

Time is measured in seconds (on my 16GB RAM, Intel Core i7 CPU @2.20 GHz laptop).  

|#threads| **over-estimate (old version)**|**over-estimate (new version)**|**by scout (new version)**|**percentage time-increase when using scout**|
|---:|---:|---:|---:|---:|
|0|         9.548760|         9.493710  |10.778510|  +13.5%  |
|1|       16.259485|        13.163708  |14.558295|  +10.6 % |
|2|         9.551608|        8.110915  |8.559207|  +5.5%  |
|3|         7.883986|        6.729505  |6.847451|  +1.9%  |
|4|         7.010394|        5.726836  |5.751568|  +0.4%  |
|5|         6.415807|        5.164772  |5.072210|  -1.8%  |
|6|         6.019867|        4.689168  |4.534729|  -3.3% |
|7|         5.786934|       4.457518  |4.260479|  -4.4% |

#matrix_pairs = 16
ntop = 1000
threshold = 0.01
nr_vocab = 17576
density = 30/n_vocab = 0.0017
n_samples = 1000000 (the number of rows of ***A***)
n_duplicates = 1000  (the number of columns of ***B***)
nnz(***A***) = 30000000  (the number of nonzero components of ***A***)
nnz(***B***) = 30000  (the number of nonzero components of ***B***)

nnz(***A***\****B***) = 47108224 +/- 18498
ntop(***A***\****B***) = 108 +/- 3
 
Now that I've done the speed-measurements properly, I see that the gains the new version has made on the old must be due to other optimizations I made for the multi-threaded functions, namely:

the old version's multi-threaded implementation in the C/C++ code used a typically very large vector of vectors (from the C++ standard template library), with length equal to the number of rows of ***A***.  This is generally not recommended.  

The new version tries to avoid this by instead using 2 small vectors of vectors, each with length equal to the number of threads, which is, typically, a much smaller number.  The result is that the used memory is leaner and less fragmented during the run.

I hope this answers your question satisfactorily.

**Comment by ParticularMiner** [comment]
Hi @Bergvca,

Here are even starker results for an even larger matrix (whose size is just below the limit of what my laptop memory can handle) that show that the new version can be _significantly_ faster than the old version:

|#threads| **over-estimate (old version)**|**over-estimate (new version)**|**by scout (new version)**|**&pm; percentage time-increase when using scout**|
|---:|---:|---:|---:|---:|
|0|48.514178|48.343654|51.316400|6.2%|
|1|58.753923|58.377917|61.448977|5.3%|
|2|37.840460|34.885811|34.919801|0.1%|
|3|31.613687|27.818065|27.046181|-2.7%|
|4|31.407376|23.677237|23.003087|-2.8%|
|5|31.088048|21.069453|20.051355|-4.8%|
|6|27.907252|19.542617|18.389929|-5.9%|
|7|28.286332|18.557715|16.895023|-8.8%|


#matrix_pairs = 16
ntop = 4&nbsp;000
threshold = 0.01
nr_vocab = 26<sup>3</sup> = 17&nbsp;576 (the number of columns of ***A*** = number of rows of ***B***)
density = 30/n_vocab = 0.0017
n_samples = 1&nbsp;000&nbsp;000 (the number of rows of ***A***)
n_duplicates = 4&nbsp;000  (the number of columns of ***B***)
nnz(***A***) = 30&nbsp;000&nbsp;000  (the number of nonzero components of ***A***)
nnz(***B***) = 120&nbsp;000  (the number of nonzero components of ***B***)

nnz(***A***\****B***) = 188&nbsp;446&nbsp;798 &pm; 44&nbsp;679   (mean and standard deviation of the total number of nonzero components of ***A***\****B*** above the threshold over 16 random matrix-pairs ***A*** and ***B***)

ntop(***A***\****B***) = 391 &pm; 15  (mean and standard deviation of the true maximum number of nonzero components per row of ***A***\****B*** above the threshold over 16 random matrix-pairs ***A*** and ***B***)

**Pull request closed without merging**
