### PR TITLE
Updated routine for increased performance

### PR DESCRIPTION
**Pull request by ParticularMiner**
See issue #21 for detailed explanation.

### CODE REVIEW

**Comment by Bergvca** [comment]
Great idea! I did not know of connected_components yet, very interesting. Because of this we can remove the _clean_groups function as well. Is that something you could add to this PR? Thanks!

**Comment by ParticularMiner** [comment]
Oops I forgot that.  Sorry!  I will remove _clean_groups and update this PR.
I'm glad you approve.

**Comment by ParticularMiner** [comment]
Done.

**Comment by Bergvca** [comment]
Many thanks!

**Pull request merged**
