### PR TITLE
updated dependency on new version of sparse_dot_topn (v0.3.1)

### PR DESCRIPTION
**Pull request by ParticularMiner**
Hi @Bergvca 

Been a while.  I hope all is well.

The new `sparse_dot_topn` is finally in!

The team at ing-bank merged my PR and even added more functionality to `sparse_dot_topn`, thereby releasing 2 versions: v0.3.0 and v0.3.1.  It's been quite an instructive and fruitful collaboration not unlike ours.

So I've updated `string_grouper` accordingly, so that this branch no longer has a dedicated subpackage that replaces `sparse_dot_topn`.  Instead I have restored its dependency on the external package `sparse_dot_topn`, albeit on the newest version v0.3.1 (see `setup.py`)

### CODE REVIEW

**Comment by ParticularMiner** [comment]
Notify @Bergvca :

The idea of `sparse_dot_topn (v0.3.1)` was to investigate the pros and cons of using the `float32` datatype instead of `float64`.  In my opinion, the precision offered by `float64` is often unnecessarily high for NLP applications.  Fortunately `TfidfVectorizer` from `sklearn.feature_extraction.text` allows the user to specify the datatype of the matrix components.

Accordingly, this PR of `string_grouper` now allows the use of either the `numpy.float32` or `numpy.float64` datatype.

Here are a few timings obtained on my modest laptop (Intel Core i7, 2.20 GHz clock speed, 16GB RAM):

### Table of average time-durations of `awesome_cossim_topn` (for the old and new versions) over 16 random samples of matrix-pairs ***A*** and ***B***.

|#threads| **(v0.2.9)<br>`float64`**|**(v0.3.0)<br>`float64`**|**(v0.3.1)<br>`float32`**|**%-age speed-increase<br>(v0.3.0 over v0.2.9)**|**%-age speed-increase<br>(`float32` \[v0.3.1\] over `float64` \[v0.3.0\])**|
|---:|---:|---:|---:|---:|---:|
|0|48.357178|45.756128|31.243680|6%|46%|
|1|84.805013|49.046593|32.823485|73%|49%|
|2|58.365927|26.116717|19.529827|123%|34%|
|3|48.586614|21.365131|14.963700|127%|43%|
|4|44.523800|18.311739|12.908124|143%|42%|
|5|42.053307|15.756574|11.992907|166%|31%|
|6|40.212938|14.098908|10.606070|185%|33%|
|7|39.031401|13.224633|9.834058|195%|34%|

#matrix_pairs = 16
ntop = 4&nbsp;000
threshold = 0.01
nr_vocab = 26<sup>3</sup> = 17&nbsp;576 (the number of columns of ***A*** = number of rows of ***B***)
density = 30/n_vocab = 0.0017
n_samples = 1&nbsp;000&nbsp;000 (the number of rows of ***A***)
n_duplicates = 4&nbsp;000  (the number of columns of ***B***)
nnz(***A***) = 30&nbsp;000&nbsp;000  (the number of nonzero components of ***A***)
nnz(***B***) = 120&nbsp;000  (the number of nonzero components of ***B***)

nnz(***A***\****B***) = 188&nbsp;446&nbsp;798 &pm; 44&nbsp;679   (mean and standard deviation of the total number of nonzero components of ***A***\****B*** above the threshold over 16 random matrix-pairs ***A*** and ***B***)

ntop(***A***\****B***) = 391 &pm; 15  (mean and standard deviation of the true maximum number of nonzero components per row of ***A***\****B*** above the threshold over 16 random matrix-pairs ***A*** and ***B***)

**Comment by Bergvca** [comment]
Hi @ParticularMiner ,

This is great, that is a crazy performance improvement! And much easier for me too review as well :) Many thanks again!

**Comment by ParticularMiner** [comment]
Hey @Bergvca!

Glad that you like it too!

By the way, the team at ING-bank plan to write a blog announcing their new versions of sparse-dot-topn and have very generously decided to promote string-grouper too. I thought you wouldn't mind them citing you as its maintainer.  If I'm mistaken please let me know.  In their draft (see https://docs.google.com/document/d/1QLSoSAf6gncJ27J9UQ5vN4Zx3Na6H92gihQ0DCb4l9s/edit#), they cite you already.



> Hi @ParticularMiner ,
> 
> 
> 
> This is great, that is a crazy performance improvement! And much easier for me too review as well :) Many thanks again!

**Comment by ParticularMiner** [comment]
Notify: @Bergvca 

See https://medium.com/wbaa/even-faster-string-comparison-2778be7fe480

**Review by Bergvca — APPROVED** [review]
As mentioned, nice work! I've tested this on my laptop (4 core i7) and on the *sec edgar dataset* and it ran in 31 minutes as opposed to 36 minutes on v0.4.0

**Comment by Bergvca** [comment]
I've merged the branche, updated the version v0.5.0 and uploaded it to pip. I also updated the codecov thingy again. Of Course no issue with the mention in the blog, interesting read!

**Comment by ParticularMiner** [comment]
> As mentioned, nice work! I've tested this on my laptop (4 core i7) and on the _sec edgar dataset_ and it ran in 31 minutes as opposed to 36 minutes on v0.4.0

Thanks! That’s consistent with my run on the same dataset: 25 minutes as opposed to 30 minutes on v0.4.0

**Pull request merged**
