### PR TITLE
optimized code and fixed bug related to input Series of length 1 (discovered by user)

### PR DESCRIPTION
**Pull request by ParticularMiner**
cc: @gw00207

Hi @Bergvca,

Please see Issue #52.  
This bug was my fault &mdash; careless use of `pandas.Dataframe.squeeze()` and `numpy.ndarray.squeeze()`.  Sorry!
Now fixed!

```python
import pandas as pd
from string_grouper import group_similar_strings
```

```python
group_similar_strings(strings_to_group=pd.Series(['hello']))
```

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>group_rep_index</th>
      <th>group_rep</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>0</td>
      <td>hello</td>
    </tr>
  </tbody>
</table>
</div>

```python
group_similar_strings(strings_to_group=pd.Series(['hello']), ignore_index=True)
```

    0    hello
    Name: group_rep, dtype: object

### CODE REVIEW

**Comment by ParticularMiner** [comment]
Notify: @Bergvca 

Also included unit test for this bug.

**Review by Bergvca — COMMENTED** [review]
I now see that this PR involves the same functions as in https://github.com/Bergvca/string_grouper/pull/51. The same comments apply but to this one. I assume then that 51 can be closed / ignored?

**Comment by ParticularMiner** [comment]
Notify @Bergvca 

Changes applied.

**Comment by ParticularMiner** [comment]
Notify @Bergvca:

Tests on sub-package `string_grouper_utils` kept outputting deprecated warnings.  So I fixed this in this PR fixes this issue.

###  BEFORE THE FIX:

```cmd
============================= test session starts =============================
platform win32 -- Python 3.9.2, pytest-6.2.3, py-1.10.0, pluggy-0.13.1
rootdir: C:\Users\heamu\eclipse-workspace\string_grouper
plugins: anyio-2.2.0
collected 16 items

string_grouper_utils\test\test_string_grouper_utils.py ................

============================== warnings summary ===============================
string_grouper_utils/test/test_string_grouper_utils.py::StringGrouperUtilTest::test_group_rep_by_timestamp_dateutil_timestamps
string_grouper_utils/test/test_string_grouper_utils.py::StringGrouperUtilTest::test_group_rep_by_timestamp_dateutil_timestamps
string_grouper_utils/test/test_string_grouper_utils.py::StringGrouperUtilTest::test_group_rep_by_timestamp_dateutil_timestamps
string_grouper_utils/test/test_string_grouper_utils.py::StringGrouperUtilTest::test_group_rep_by_timestamp_dateutil_timestamps
string_grouper_utils/test/test_string_grouper_utils.py::StringGrouperUtilTest::test_group_rep_by_timestamp_dateutil_timestamps
string_grouper_utils/test/test_string_grouper_utils.py::StringGrouperUtilTest::test_group_rep_by_timestamp_dateutil_timestamps
  C:\Users\heamu\eclipse-workspace\string_grouper\string_grouper_utils\string_grouper_utils.py:152: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
    return timestamps.transform(lambda x: np.datetime64(x))

string_grouper_utils/test/test_string_grouper_utils.py: 18 warnings
  C:\Users\heamu\eclipse-workspace\string_grouper\string_grouper_utils\string_grouper_utils.py:146: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
    return timestamps.transform(lambda x: np.datetime64(parse(x, parserinfo, **kwargs)))

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================= 16 passed, 24 warnings in 0.83s =======================
```

### AFTER THE FIX:

```cmd
============================= test session starts =============================
platform win32 -- Python 3.9.2, pytest-6.2.3, py-1.10.0, pluggy-0.13.1
rootdir: C:\Users\heamu\eclipse-workspace\string_grouper
plugins: anyio-2.2.0
collected 16 items

string_grouper_utils\test\test_string_grouper_utils.py ................

============================= 16 passed in 0.85s ==============================
```

**Comment by ParticularMiner** [comment]
Hi @Bergvca 

I'm sorry that the number of code changes increased so much: I just discovered flake8 code-analysis and most of the changes are simply due to that.
:)

**Pull request merged**
