### PR TITLE
Pairwise Similarity Computation (User Request)

### PR DESCRIPTION
**Pull request by ParticularMiner**
Hi @Bergvca ,

Please see the [message](https://github.com/Bergvca/string_grouper/issues/39#issue-842498195) by @KiraJYQiu in Issue #39.

I'm not sure if @KiraJYQiu's request is functionality you want added to `string_grouper`.  Nevertheless it is brief and simple enough to code that I've easily added it to the code in this branch "dot".

You may merge this PR if you think it's useful.  Here's a brief demo:

```python
import pandas as pd
from string_grouper import compute_pairwise_similarities
```

```python
pair_s = pd.DataFrame(
    [
        ('Mega Enterprises Corporation', 'Mega Enterprises Corporation'),
        ('Hyper Startup Inc.', 'Hyper Startup Incorporated'),
        ('Hyper Startup Inc.', 'Hyper Startup Inc.'),
        ('Hyper Startup Inc.', 'Hyper-Startup Inc.'),
        ('Hyper Hyper Inc.', 'Hyper Hyper Inc.'),
        ('Mega Enterprises Corporation', 'Mega Enterprises Corp.')
   ],
   columns=('left', 'right')
)

pair_s
```

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>left</th>
      <th>right</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>Mega Enterprises Corporation</td>
      <td>Mega Enterprises Corporation</td>
    </tr>
    <tr>
      <th>1</th>
      <td>Hyper Startup Inc.</td>
      <td>Hyper Startup Incorporated</td>
    </tr>
    <tr>
      <th>2</th>
      <td>Hyper Startup Inc.</td>
      <td>Hyper Startup Inc.</td>
    </tr>
    <tr>
      <th>3</th>
      <td>Hyper Startup Inc.</td>
      <td>Hyper-Startup Inc.</td>
    </tr>
    <tr>
      <th>4</th>
      <td>Hyper Hyper Inc.</td>
      <td>Hyper Hyper Inc.</td>
    </tr>
    <tr>
      <th>5</th>
      <td>Mega Enterprises Corporation</td>
      <td>Mega Enterprises Corp.</td>
    </tr>
  </tbody>
</table>
</div>

```python
pair_s['similarity'] = compute_pairwise_similarities(pair_s['left'], pair_s['right'])
pair_s
```

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>left</th>
      <th>right</th>
      <th>similarity</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>Mega Enterprises Corporation</td>
      <td>Mega Enterprises Corporation</td>
      <td>1.000000</td>
    </tr>
    <tr>
      <th>1</th>
      <td>Hyper Startup Inc.</td>
      <td>Hyper Startup Incorporated</td>
      <td>0.633620</td>
    </tr>
    <tr>
      <th>2</th>
      <td>Hyper Startup Inc.</td>
      <td>Hyper Startup Inc.</td>
      <td>1.000000</td>
    </tr>
    <tr>
      <th>3</th>
      <td>Hyper Startup Inc.</td>
      <td>Hyper-Startup Inc.</td>
      <td>1.000000</td>
    </tr>
    <tr>
      <th>4</th>
      <td>Hyper Hyper Inc.</td>
      <td>Hyper Hyper Inc.</td>
      <td>1.000000</td>
    </tr>
    <tr>
      <th>5</th>
      <td>Mega Enterprises Corporation</td>
      <td>Mega Enterprises Corp.</td>
      <td>0.826463</td>
    </tr>
  </tbody>
</table>
</div>

### CODE REVIEW

**Comment by probablyfine** [comment]
This is great, thanks for sharing! I've been doing something similar for my use case for a while now, but my solution is not as fast or as elegant as yours. I'd love to see this make its way into the main branch since I use this functionality multiple times per week.

**Comment by Bergvca** [comment]
This looks good to me, and @probablyfine already validated that this is useful so good for me too merge. Am I correct that all 3 of your PR's are basically the same branch? If that is the case let me know if you are ready with all 3. Since they update the documentation as well I think it is best to update pypi shortly afterwards (so pypi and the master branch are synced).

**Comment by ParticularMiner** [comment]
Hi @Bergvca ,

I’m glad you approve of all the PR’s.  Currently they are each on separate branches.  But to make things easiest for you, let me merge all 3 of them into a single branch so you can merge that single branch (containing everything) into yours.  

Regarding backward compatibility, if you feel, between now and then, that we should change the default for ignore_index to True, do let me know.  You most likely know better how your code is being used out there and by whom.

Wishing you a good week after Easter!  Cheers!

**Comment by ParticularMiner** [comment]
Hi @probablyfine,

Thanks for validating this PR and the compliment!  These will soon be added to the main branch.

**Comment by Bergvca** [comment]
Hi @ParticularMiner,

No need for a single branch, I think it's nicer to have separate.

Cheers to you as well!

**Comment by ParticularMiner** [comment]
Alright.  Then let's merge the PR's one by one.  

I'd recommend the following merge order:
1. index (PR #41)  Full index-functionality
2. dot (PR #40)  Pairwise similarity computation
3. sim_zero (PR #43)  Zero-similarity bug

I wasn't very careful with my commits, so I expect there to be conflicts between the three branches which only I can resolve.   But now worries, I can resolve these conflicts by syncing my local master branch with yours after each PR-merge you make, and then carefully merging my synced master branch into the next PR branch to be merged.  I hope that's OK?

**Comment by ParticularMiner** [comment]
If it helps, here's how the branches look like currently:

**Comment by Bergvca** [comment]
Hi @ParticularMiner  - as you mentioned there seem to be some conflicts :)

**Comment by ParticularMiner** [comment]
Hi @Bergvca,

I've fixed this one.  So you can go ahead and merge.  Sorry for the inconvenience.

> Hi @ParticularMiner - as you mentioned there seem to be some conflicts :)

**Pull request merged**
