### PR TITLE
Fixed a bug which occurs when min_similarity=0 (User discovery)

### PR DESCRIPTION
**Pull request by ParticularMiner**
Hi @Bergvca,

Initially I thought this Issue (#42 by @nbcvijanovic) was not very important.  But on second thought I think it is actually a bug which needs fixing, or it might lead to unexpected consequences.
So here is a fix for your review.

# When min_similarity &le; 0 and include_zeroes = [True | False])

```python
import pandas as pd
import numpy as np
from string_grouper import StringGrouper
```

```python
companies_df = pd.read_csv('data/sec__edgar_company_info.csv')[0:50000]
```

```python
master = companies_df['Company Name']
master_id = companies_df['Line Number']
duplicates = pd.Series(["ADVISORS DISCIPLINED TRUST", "ADVISORS DISCIPLINED TRUST '18"])
duplicates_id = pd.Series([3, 5])
```

#### When ID's are passed as arguments:
By default, zero-similarity matches are found and output when `min_similarity = 0`:

```python
string_grouper = StringGrouper(
    master = master,
    duplicates=duplicates,
    master_id=master_id,
    duplicates_id=duplicates_id,
    ignore_index=True,
    min_similarity = 0,
    max_n_matches = 10000,
    regex = "[,-./#]"
).fit()
string_grouper.get_matches()
```

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>left_Company Name</th>
      <th>left_Line Number</th>
      <th>similarity</th>
      <th>right_id</th>
      <th>right_side</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>#1 ARIZONA DISCOUNT PROPERTIES LLC</td>
      <td>3</td>
      <td>0.091157</td>
      <td>3</td>
      <td>ADVISORS DISCIPLINED TRUST</td>
    </tr>
    <tr>
      <th>1</th>
      <td>#1 ARIZONA DISCOUNT PROPERTIES LLC</td>
      <td>3</td>
      <td>0.063861</td>
      <td>5</td>
      <td>ADVISORS DISCIPLINED TRUST '18</td>
    </tr>
    <tr>
      <th>2</th>
      <td>05 CAT THIEF/GOLD IN MY STARS LLC</td>
      <td>21</td>
      <td>0.015313</td>
      <td>3</td>
      <td>ADVISORS DISCIPLINED TRUST</td>
    </tr>
    <tr>
      <th>3</th>
      <td>05 CAT THIEF/GOLD IN MY STARS LLC</td>
      <td>21</td>
      <td>0.010728</td>
      <td>5</td>
      <td>ADVISORS DISCIPLINED TRUST '18</td>
    </tr>
    <tr>
      <th>4</th>
      <td>05 DIXIE UNION/UNDER FIRE LLC</td>
      <td>22</td>
      <td>0.025397</td>
      <td>3</td>
      <td>ADVISORS DISCIPLINED TRUST</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>99995</th>
      <td>ALLDREDGE WILLIAM T</td>
      <td>21746</td>
      <td>0.000000</td>
      <td>3</td>
      <td>ADVISORS DISCIPLINED TRUST</td>
    </tr>
    <tr>
      <th>99996</th>
      <td>ALLEN SAMUEL R</td>
      <td>22183</td>
      <td>0.000000</td>
      <td>5</td>
      <td>ADVISORS DISCIPLINED TRUST '18</td>
    </tr>
    <tr>
      <th>99997</th>
      <td>ATSP INNOVATIONS, LLC</td>
      <td>45273</td>
      <td>0.000000</td>
      <td>5</td>
      <td>ADVISORS DISCIPLINED TRUST '18</td>
    </tr>
    <tr>
      <th>99998</th>
      <td>ATLAS IDF, LP</td>
      <td>44877</td>
      <td>0.000000</td>
      <td>5</td>
      <td>ADVISORS DISCIPLINED TRUST '18</td>
    </tr>
    <tr>
      <th>99999</th>
      <td>AU LEO Y</td>
      <td>45535</td>
      <td>0.000000</td>
      <td>5</td>
      <td>ADVISORS DISCIPLINED TRUST '18</td>
    </tr>
  </tbody>
</table>
<p>100000 rows &times; 5 columns</p>
</div>

#### `StringGrouper` also includes option `include_zeroes`:

```python
string_grouper = StringGrouper(
    master = master,
    duplicates=duplicates,
    master_id=master_id,
    duplicates_id=duplicates_id,
    ignore_index=True,
    min_similarity = 0,
    max_n_matches = 10000,
    regex = "[,-./#]",
    include_zeroes = False
).fit()
string_grouper.get_matches()
```

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>left_Company Name</th>
      <th>left_Line Number</th>
      <th>similarity</th>
      <th>right_id</th>
      <th>right_side</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>#1 ARIZONA DISCOUNT PROPERTIES LLC</td>
      <td>3</td>
      <td>0.091157</td>
      <td>3</td>
      <td>ADVISORS DISCIPLINED TRUST</td>
    </tr>
    <tr>
      <th>1</th>
      <td>#1 ARIZONA DISCOUNT PROPERTIES LLC</td>
      <td>3</td>
      <td>0.063861</td>
      <td>5</td>
      <td>ADVISORS DISCIPLINED TRUST '18</td>
    </tr>
    <tr>
      <th>2</th>
      <td>05 CAT THIEF/GOLD IN MY STARS LLC</td>
      <td>21</td>
      <td>0.015313</td>
      <td>3</td>
      <td>ADVISORS DISCIPLINED TRUST</td>
    </tr>
    <tr>
      <th>3</th>
      <td>05 CAT THIEF/GOLD IN MY STARS LLC</td>
      <td>21</td>
      <td>0.010728</td>
      <td>5</td>
      <td>ADVISORS DISCIPLINED TRUST '18</td>
    </tr>
    <tr>
      <th>4</th>
      <td>05 DIXIE UNION/UNDER FIRE LLC</td>
      <td>22</td>
      <td>0.025397</td>
      <td>3</td>
      <td>ADVISORS DISCIPLINED TRUST</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>28754</th>
      <td>BAAPLIFE3-2015, LLC</td>
      <td>49976</td>
      <td>0.021830</td>
      <td>5</td>
      <td>ADVISORS DISCIPLINED TRUST '18</td>
    </tr>
    <tr>
      <th>28755</th>
      <td>BAAPLIFE4-2016, LLC</td>
      <td>49977</td>
      <td>0.030983</td>
      <td>3</td>
      <td>ADVISORS DISCIPLINED TRUST</td>
    </tr>
    <tr>
      <th>28756</th>
      <td>BAAPLIFE4-2016, LLC</td>
      <td>49977</td>
      <td>0.021706</td>
      <td>5</td>
      <td>ADVISORS DISCIPLINED TRUST '18</td>
    </tr>
    <tr>
      <th>28757</th>
      <td>BABA JOE DIAMOND VENTURES US INC.</td>
      <td>49989</td>
      <td>0.027064</td>
      <td>3</td>
      <td>ADVISORS DISCIPLINED TRUST</td>
    </tr>
    <tr>
      <th>28758</th>
      <td>BABA JOE DIAMOND VENTURES US INC.</td>
      <td>49989</td>
      <td>0.018960</td>
      <td>5</td>
      <td>ADVISORS DISCIPLINED TRUST '18</td>
    </tr>
  </tbody>
</table>
<p>28759 rows &times; 5 columns</p>
</div>

#### `get_matches` option `include_zeroes` can override `StringGrouper` default:

```python
string_grouper.get_matches(include_zeroes=True)
```

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>left_Company Name</th>
      <th>left_Line Number</th>
      <th>similarity</th>
      <th>right_id</th>
      <th>right_side</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>#1 ARIZONA DISCOUNT PROPERTIES LLC</td>
      <td>3</td>
      <td>0.091157</td>
      <td>3</td>
      <td>ADVISORS DISCIPLINED TRUST</td>
    </tr>
    <tr>
      <th>1</th>
      <td>#1 ARIZONA DISCOUNT PROPERTIES LLC</td>
      <td>3</td>
      <td>0.063861</td>
      <td>5</td>
      <td>ADVISORS DISCIPLINED TRUST '18</td>
    </tr>
    <tr>
      <th>2</th>
      <td>05 CAT THIEF/GOLD IN MY STARS LLC</td>
      <td>21</td>
      <td>0.015313</td>
      <td>3</td>
      <td>ADVISORS DISCIPLINED TRUST</td>
    </tr>
    <tr>
      <th>3</th>
      <td>05 CAT THIEF/GOLD IN MY STARS LLC</td>
      <td>21</td>
      <td>0.010728</td>
      <td>5</td>
      <td>ADVISORS DISCIPLINED TRUST '18</td>
    </tr>
    <tr>
      <th>4</th>
      <td>05 DIXIE UNION/UNDER FIRE LLC</td>
      <td>22</td>
      <td>0.025397</td>
      <td>3</td>
      <td>ADVISORS DISCIPLINED TRUST</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>99995</th>
      <td>ALLDREDGE WILLIAM T</td>
      <td>21746</td>
      <td>0.000000</td>
      <td>3</td>
      <td>ADVISORS DISCIPLINED TRUST</td>
    </tr>
    <tr>
      <th>99996</th>
      <td>ALLEN SAMUEL R</td>
      <td>22183</td>
      <td>0.000000</td>
      <td>5</td>
      <td>ADVISORS DISCIPLINED TRUST '18</td>
    </tr>
    <tr>
      <th>99997</th>
      <td>ATSP INNOVATIONS, LLC</td>
      <td>45273</td>
      <td>0.000000</td>
      <td>5</td>
      <td>ADVISORS DISCIPLINED TRUST '18</td>
    </tr>
    <tr>
      <th>99998</th>
      <td>ATLAS IDF, LP</td>
      <td>44877</td>
      <td>0.000000</td>
      <td>5</td>
      <td>ADVISORS DISCIPLINED TRUST '18</td>
    </tr>
    <tr>
      <th>99999</th>
      <td>AU LEO Y</td>
      <td>45535</td>
      <td>0.000000</td>
      <td>5</td>
      <td>ADVISORS DISCIPLINED TRUST '18</td>
    </tr>
  </tbody>
</table>
<p>100000 rows &times; 5 columns</p>
</div>

#### When no ID's are passed as arguments and indexes are not set:
Default indexes are output:

```python
string_grouper = StringGrouper(
    master = master,
    duplicates=duplicates,
    min_similarity = 0,
    max_n_matches = 10000,
    regex = "[,-./#]"
).fit()
string_grouper.get_matches()
```

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>left_index</th>
      <th>left_Company Name</th>
      <th>similarity</th>
      <th>right_side</th>
      <th>right_index</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>2</td>
      <td>#1 ARIZONA DISCOUNT PROPERTIES LLC</td>
      <td>0.091157</td>
      <td>ADVISORS DISCIPLINED TRUST</td>
      <td>0</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2</td>
      <td>#1 ARIZONA DISCOUNT PROPERTIES LLC</td>
      <td>0.063861</td>
      <td>ADVISORS DISCIPLINED TRUST '18</td>
      <td>1</td>
    </tr>
    <tr>
      <th>2</th>
      <td>20</td>
      <td>05 CAT THIEF/GOLD IN MY STARS LLC</td>
      <td>0.015313</td>
      <td>ADVISORS DISCIPLINED TRUST</td>
      <td>0</td>
    </tr>
    <tr>
      <th>3</th>
      <td>20</td>
      <td>05 CAT THIEF/GOLD IN MY STARS LLC</td>
      <td>0.010728</td>
      <td>ADVISORS DISCIPLINED TRUST '18</td>
      <td>1</td>
    </tr>
    <tr>
      <th>4</th>
      <td>21</td>
      <td>05 DIXIE UNION/UNDER FIRE LLC</td>
      <td>0.025397</td>
      <td>ADVISORS DISCIPLINED TRUST</td>
      <td>0</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>99995</th>
      <td>21745</td>
      <td>ALLDREDGE WILLIAM T</td>
      <td>0.000000</td>
      <td>ADVISORS DISCIPLINED TRUST</td>
      <td>0</td>
    </tr>
    <tr>
      <th>99996</th>
      <td>22182</td>
      <td>ALLEN SAMUEL R</td>
      <td>0.000000</td>
      <td>ADVISORS DISCIPLINED TRUST '18</td>
      <td>1</td>
    </tr>
    <tr>
      <th>99997</th>
      <td>45272</td>
      <td>ATSP INNOVATIONS, LLC</td>
      <td>0.000000</td>
      <td>ADVISORS DISCIPLINED TRUST '18</td>
      <td>1</td>
    </tr>
    <tr>
      <th>99998</th>
      <td>44876</td>
      <td>ATLAS IDF, LP</td>
      <td>0.000000</td>
      <td>ADVISORS DISCIPLINED TRUST '18</td>
      <td>1</td>
    </tr>
    <tr>
      <th>99999</th>
      <td>45534</td>
      <td>AU LEO Y</td>
      <td>0.000000</td>
      <td>ADVISORS DISCIPLINED TRUST '18</td>
      <td>1</td>
    </tr>
  </tbody>
</table>
<p>100000 rows &times; 5 columns</p>
</div>

#### When no ID's are passed as arguments but indexes are set:
Indexes are output:

```python
master.index = pd.Index(master_id)
duplicates.index = pd.Index(duplicates_id)
string_grouper = StringGrouper(
    master = master,
    duplicates=duplicates,
    min_similarity = 0,
    max_n_matches = 10000,
    regex = "[,-./#]"
).fit()
string_grouper.get_matches()
```

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>left_Line Number</th>
      <th>left_Company Name</th>
      <th>similarity</th>
      <th>right_side</th>
      <th>right_index</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>3</td>
      <td>#1 ARIZONA DISCOUNT PROPERTIES LLC</td>
      <td>0.091157</td>
      <td>ADVISORS DISCIPLINED TRUST</td>
      <td>3</td>
    </tr>
    <tr>
      <th>1</th>
      <td>3</td>
      <td>#1 ARIZONA DISCOUNT PROPERTIES LLC</td>
      <td>0.063861</td>
      <td>ADVISORS DISCIPLINED TRUST '18</td>
      <td>5</td>
    </tr>
    <tr>
      <th>2</th>
      <td>21</td>
      <td>05 CAT THIEF/GOLD IN MY STARS LLC</td>
      <td>0.015313</td>
      <td>ADVISORS DISCIPLINED TRUST</td>
      <td>3</td>
    </tr>
    <tr>
      <th>3</th>
      <td>21</td>
      <td>05 CAT THIEF/GOLD IN MY STARS LLC</td>
      <td>0.010728</td>
      <td>ADVISORS DISCIPLINED TRUST '18</td>
      <td>5</td>
    </tr>
    <tr>
      <th>4</th>
      <td>22</td>
      <td>05 DIXIE UNION/UNDER FIRE LLC</td>
      <td>0.025397</td>
      <td>ADVISORS DISCIPLINED TRUST</td>
      <td>3</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>99995</th>
      <td>21746</td>
      <td>ALLDREDGE WILLIAM T</td>
      <td>0.000000</td>
      <td>ADVISORS DISCIPLINED TRUST</td>
      <td>3</td>
    </tr>
    <tr>
      <th>99996</th>
      <td>22183</td>
      <td>ALLEN SAMUEL R</td>
      <td>0.000000</td>
      <td>ADVISORS DISCIPLINED TRUST '18</td>
      <td>5</td>
    </tr>
    <tr>
      <th>99997</th>
      <td>45273</td>
      <td>ATSP INNOVATIONS, LLC</td>
      <td>0.000000</td>
      <td>ADVISORS DISCIPLINED TRUST '18</td>
      <td>5</td>
    </tr>
    <tr>
      <th>99998</th>
      <td>44877</td>
      <td>ATLAS IDF, LP</td>
      <td>0.000000</td>
      <td>ADVISORS DISCIPLINED TRUST '18</td>
      <td>5</td>
    </tr>
    <tr>
      <th>99999</th>
      <td>45535</td>
      <td>AU LEO Y</td>
      <td>0.000000</td>
      <td>ADVISORS DISCIPLINED TRUST '18</td>
      <td>5</td>
    </tr>
  </tbody>
</table>
<p>100000 rows &times; 5 columns</p>
</div>

### CODE REVIEW

**Comment by ParticularMiner** [comment]
Done. 

I have to say, I still don't fully understand git/github merge procedures.  Do you? Will have to read up on it further. 

> Hi @ParticularMiner - now this one :)

**Comment by ParticularMiner** [comment]
> Done.
> 
> I have to say, I still don't fully understand git/github merge procedures. Do you? Will have to read up on it further.
> 
> > Hi @ParticularMiner - now this one :)

Hi @Bergvca ,

I’ve never had to approve and merge a PR myself because I’ve never hosted my own unforked repository.  Perhaps someday!  :)  But it seems that as soon as you approve and merge one PR all other pending PRs suddenly find themselves in conflict with your newly updated master branch.

This is understandable since all pending PRs are still based on the previous revision of the newly updated master branch.  But what is curious is why GitHub cannot automatically figure out that some conflicts are certainly “fake”, in particular when some pending PR was in fact already based on the just merged PR.

I can understand that a git merge may not always accept all changes from the merging PR.  (I’m not sure if it’s the same for a GitHub PR merge.)  But in our case, you clearly accepted all the.changes of my PR.

I wonder if there’s a way for GitHub to stop flagging such spurious conflicts, as it induces hesitation when attempting to merge the other pending PRs; and furthermore, causes the creator of the pending PR to resort to some needless roundabout ways to resolve these fake conflicts.

**Comment by ParticularMiner** [comment]
attention: @Bergvca , @nbcvijanovic

I just inserted a CRITICAL warning when `max_n_matches` is too small and `min_similarity <= 0` and `include_zeroes= True`

**Comment by Bergvca** [comment]
> > Done.
> > I have to say, I still don't fully understand git/github merge procedures. Do you? Will have to read up on it further.
> > > Hi @ParticularMiner - now this one :)
> 
> Hi @Bergvca ,
> 
> I’ve never had to approve and merge a PR myself because I’ve never hosted my own unforked repository. Perhaps someday! :) But it seems that as soon as you approve and merge one PR all other pending PRs suddenly find themselves in conflict with your newly updated master branch.
> 
> This is understandable since all pending PRs are still based on the previous revision of the newly updated master branch. But what is curious is why GitHub cannot automatically figure out that some conflicts are certainly “fake”, in particular when some pending PR was in fact already based on the just merged PR.
> 
> I can understand that a git merge may not always accept all changes from the merging remote branch. (I’m not sure if it’s the same for a GitHub PR merge.) But in our case, you clearly accepted all the changes of my PR.
> 
> I wonder if there’s a way for GitHub to stop flagging such spurious conflicts, as it induces hesitation when attempting to merge the other pending PRs; and furthermore, causes the creator of the pending PR to resort to some needless roundabout ways to resolve these fake conflicts.

Hi @ParticularMiner 

Git doesn't stop being difficult I believe. It's like a steep learning curve, that is secretly not a curve at all, more of a line :) 

I don't really understand what went wrong there either, since it seemed (to me at least) that all your branches were based on the same branch, so there should be no conflicts. Normally, right before I am ready to create a PR, I merge the master branch in my new branch (to check for conflicts). I think that is what you did as well. After that I would think that any other branches based on the first branch (that doesn't have any conflicts), would themselves also not have any conflicts with the master branch, as long as they don't have any conflicts with the first branch.

**Comment by ParticularMiner** [comment]
Hi @Bergvca 

> Git doesn't stop being difficult I believe. It's like a steep learning curve, that is secretly not a curve at all, more of a line :)

That's certainly my experience too.  :)

Anyway, I've asked this question on [GitHub community forum](https://github.community/t/fake-conflicts-after-pr-merge/173274) too, but I'm yet to get a reply.

**Comment by dvencappa** [comment]
Hi Bergvca,
I was trying to implement a match between two panda dataset through the following command (both have columns compname common to them):

matches = match_strings(pats['compname'], famef['compname'])

However, I got the following message:

  File "C:\Anaconda3\lib\site-packages\string_grouper\string_grouper.py", line 218, in __init__
    raise TypeError('Input does not consist of pandas.Series containing only Strings')

TypeError: Input does not consist of pandas.Series containing only Strings

I am unable to make sense of this. Both pats and famef are text files read in via pd.read_csv and I explicitly declared the column compname to be string. I am not sure how to interpret and fix the above. Can you help please?

Many thanks,
Dev

**Comment by ParticularMiner** [comment]
Hi @dvencappa,

It is difficult for me to be absolutely certain what the source of the problem is.  However, as the error message says, it is possible that some of the data are not strings.  You can see which ones by running the following:

`print(pats['compname'][pats['compname'].to_frame().applymap(lambda x: not isinstance(x, str)).squeeze()])`

`print(famef['compname'][famef['compname'].to_frame().applymap(lambda x: not isinstance(x, str)).squeeze()])`

Hope this helps.

**Comment by dvencappa** [comment]
Hi @bergvca,
thank you for your prompt response. I used your codes below to check my data sets and your codes are exactly what I needed as they revealed one of the datasets contained missing values (<NA>) which is what I guessed threw the error message. I have now corrected the data sets and your string_grouper command runs like a charm - it  has a high degree of accuracy and is very fast! Thank you for taking the time to develop these libraries to help other people use Python more effectively.
Regards,Dev

    On Thursday, 22 April 2021, 01:31:08 GMT-6, ParticularMiner ***@***.***> wrote:  
 
 


Hi @dvencappa,

It is difficult for me to be absolutely certain what the source of the problem is. However, as the error message says, it is possible that some of the data are not strings. You can see which ones by running the following:

print(pats['compname'][pats['compname'].to_frame().applymap(lambda x: not isinstance(x, str)).squeeze()])

print(famef['compname'][famef['compname'].to_frame().applymap(lambda x: not isinstance(x, str)).squeeze()])

Hope this helps.

**Comment by ParticularMiner** [comment]
Thanks @dvencappa !   Glad to know your problem is solved. :)

**Pull request merged**
